AngelBobExtended.recipe.create_subgroup("ABEtech",1,"bob-intermediate-products")
AngelBobExtended.recipe.create_subgroup("ABEtech",2,"bob-intermediate-products")

AngelBobExtended.item.create_item("tech-component-red","ABEtech1")
AngelBobExtended.item.create_item("tech-component-multi","ABEtech2")
AngelBobExtended.item.create_item("tech-component-multi-2","ABEtech2")
AngelBobExtended.item.create_item("tech-component-multi-3","ABEtech2")
AngelBobExtended.item.create_item("tech-component-multi-4","ABEtech2")
AngelBobExtended.item.create_item("tech-component-multi-5","ABEtech2")
AngelBobExtended.item.create_item("tech-component-green","ABEtech1")
AngelBobExtended.item.create_item("tech-component-blue","ABEtech1")
AngelBobExtended.item.create_item("tech-component-gray","ABEtech1")
AngelBobExtended.item.create_item("tech-component-purple","ABEtech1")
AngelBobExtended.item.create_item("tech-component-yellow","ABEtech1")
AngelBobExtended.item.create_item("tech-component-pink","ABEtech1")
AngelBobExtended.item.create_item("tech-component-gold","ABEtech1")