
local function replaceMachine()
  AngelBobExtended.recipe.addtorecipe("assembling-machine-1",{"stuffed-1",1})
  AngelBobExtended.recipe.addtorecipe("assembling-machine-2",{"stuffed-2",1})
  AngelBobExtended.recipe.addtorecipe("assembling-machine-3",{"stuffed-3",1})
  AngelBobExtended.recipe.addtorecipe("assembling-machine-4",{"stuffed-3",1})
  AngelBobExtended.recipe.addtorecipe("assembling-machine-5",{"stuffed-4",1})
  AngelBobExtended.recipe.addtorecipe("assembling-machine-6",{"stuffed-5",1})
  AngelBobExtended.recipe.addtorecipe("rocket-silo",{{"assembling-machine-6",100},{"reinforced-5",180},{"stuffed-5",40},{"heat-resistant-5",80},{"plumbing-5",20}})
  
  AngelBobExtended.recipe.addtorecipe("solar-panel",{{"silicon-wafer",40},{"glass",10}})
  AngelBobExtended.recipe.addtorecipe("solar-panel-small",{{"silicon-wafer",20},{"glass",5}})
  AngelBobExtended.recipe.addtorecipe("solar-panel-large",{{"silicon-wafer",80},{"glass",20}})
  AngelBobExtended.recipe.addtorecipe("storage-tank", {"plumbing-2", 2})
  AngelBobExtended.recipe.addtorecipe("storage-tank-2", {"plumbing-3", 4})
  AngelBobExtended.recipe.addtorecipe("storage-tank-3", {"plumbing-4", 4})
  AngelBobExtended.recipe.addtorecipe("storage-tank-4", {"plumbing-5", 4})
  
  AngelBobExtended.recipe.addtorecipe("storage-tank-all-corners", {"plumbing-2", 2})
  AngelBobExtended.recipe.addtorecipe("storage-tank-all-corners-2", {"plumbing-3", 4})
  AngelBobExtended.recipe.addtorecipe("storage-tank-all-corners-3", {"plumbing-4", 4})
  AngelBobExtended.recipe.addtorecipe("storage-tank-all-corners-4", {"plumbing-5", 4})
  
  AngelBobExtended.recipe.addtorecipe("angels-warehouse", {"primitive", 10})
  AngelBobExtended.recipe.addtorecipe("angels-pressure-tank-1", {"basic", 20})
  AngelBobExtended.recipe.addtorecipe("silo", {"primitive", 2})
  
  AngelBobExtended.recipe.addtorecipe("electronics-machine-1", {"stuffed-1", 5})
  AngelBobExtended.recipe.addtorecipe("electronics-machine-2", {"stuffed-3", 5})
  AngelBobExtended.recipe.addtorecipe("electronics-machine-3", {"stuffed-4", 5})
  
  AngelBobExtended.recipe.addtorecipe("beacon", {"stuffed-3", 10})
  AngelBobExtended.recipe.addtorecipe("beacon-2", {"stuffed-4", 10})
  AngelBobExtended.recipe.addtorecipe("beacon-3", {"stuffed-5", 10})
  
  AngelBobExtended.recipe.addtorecipe("liquifier", {{"chemical-1", 1},{"stuffed-1", 1},{"plumbing-1", 1}})
  AngelBobExtended.recipe.addtorecipe("liquifier-2", {{"chemical-2", 1},{"stuffed-2", 1},{"plumbing-2", 1}})
  AngelBobExtended.recipe.addtorecipe("liquifier-3", {{"chemical-3", 1},{"stuffed-3", 1},{"plumbing-3", 1}})
  AngelBobExtended.recipe.addtorecipe("liquifier-4", {{"chemical-4", 1},{"stuffed-4", 1},{"plumbing-4", 1}})
  
  
  AngelBobExtended.recipe.addtorecipe("oil-refinery", {{"reinforced-2", 1},{"stuffed-2", 1},{"chemical-2", 1},{"heat-resistant-2", 1},{"plumbing-2", 1}})
  AngelBobExtended.recipe.addtorecipe("oil-refinery-2", {{"reinforced-3", 1},{"stuffed-3", 1},{"chemical-3", 1},{"heat-resistant-3", 1},{"plumbing-3", 1}})
  AngelBobExtended.recipe.addtorecipe("oil-refinery-3", {{"reinforced-4", 2},{"stuffed-4", 2},{"chemical-4", 2},{"heat-resistant-4", 2},{"plumbing-4", 2}})
  AngelBobExtended.recipe.addtorecipe("oil-refinery-4", {{"reinforced-5", 2},{"stuffed-5", 2},{"chemical-5", 2},{"heat-resistant-5", 2},{"plumbing-5", 2}})
  
  AngelBobExtended.recipe.addtorecipe("electric-furnace", {"stuffed-3", 4})
  AngelBobExtended.recipe.addtorecipe("electric-furnace-2", {"stuffed-4", 4})
  AngelBobExtended.recipe.addtorecipe("electric-furnace-3", {"stuffed-5", 4})
  
  AngelBobExtended.recipe.addtorecipe("electrolyser", {{"stuffed-1", 1},{"chemical-1", 2},{"plumbing-1", 2}})
  AngelBobExtended.recipe.addtorecipe("electrolyser-2", {{"stuffed-2", 1},{"chemical-2", 2},{"plumbing-2", 2}})
  AngelBobExtended.recipe.addtorecipe("electrolyser-3", {{"stuffed-3", 1},{"chemical-3", 2},{"plumbing-3", 2}})
  AngelBobExtended.recipe.addtorecipe("electrolyser-4", {{"stuffed-4", 1},{"chemical-4", 2},{"plumbing-4", 2}})
  
  AngelBobExtended.recipe.addtorecipe("sintering-oven", {{"heat-resistant-2", 1},{"stuffed-2", 1},{"mechanical-2", 1}})
  AngelBobExtended.recipe.addtorecipe("sintering-oven-2", {{"heat-resistant-3", 1},{"stuffed-3", 1},{"mechanical-3", 1}})
  AngelBobExtended.recipe.addtorecipe("sintering-oven-3", {{"heat-resistant-4", 1},{"stuffed-4", 1},{"mechanical-4", 1}})
  AngelBobExtended.recipe.addtorecipe("sintering-oven-4", {{"heat-resistant-5", 1},{"stuffed-5", 1},{"mechanical-5", 1}})

  
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine", {"heat-resistant-2", 1})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine", {"mechanical-2", 1})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-2", {"heat-resistant-3", 1})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-2", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-2", {"mechanical-3", 1})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-3", {"heat-resistant-3", 2})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-3", {"stuffed-3", 2})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-3", {"mechanical-3", 2})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-4", {"heat-resistant-4", 2})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-4", {"stuffed-4", 2})
  AngelBobExtended.recipe.addtorecipe("strand-casting-machine-4", {"mechanical-4", 2})
  
  AngelBobExtended.recipe.addtorecipe("cooling-tower", {"heat-resistant-3", 1})
  AngelBobExtended.recipe.addtorecipe("cooling-tower", {"plumbing-3", 2})
  
  AngelBobExtended.recipe.addtorecipe("electric-mixing-furnace", {"stuffed-3", 4})
  AngelBobExtended.recipe.addtorecipe("electric-chemical-furnace", {"stuffed-3", 3})
  AngelBobExtended.recipe.addtorecipe("electric-chemical-furnace", {"chemical-3", 3})
  
  AngelBobExtended.recipe.addtorecipe("electric-chemical-mixing-furnace", {"stuffed-4", 6})
  AngelBobExtended.recipe.addtorecipe("electric-chemical-mixing-furnace", {"chemical-4", 6})
  AngelBobExtended.recipe.addtorecipe("electric-chemical-mixing-furnace-2", {"stuffed-5", 6})
  AngelBobExtended.recipe.addtorecipe("electric-chemical-mixing-furnace-2", {"chemical-5", 6})
end
local function replaceMining()
  AngelBobExtended.recipe.addtorecipe("electric-mining-drill", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("electric-mining-drill", {"mechanical-1", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-1", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-1", {"mechanical-2", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-2", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-2", {"mechanical-3", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-3", {"stuffed-4", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-3", {"mechanical-4", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-4", {"mechanical-5", 1})
  AngelBobExtended.recipe.addtorecipe("bob-mining-drill-4", {"stuffed-5", 1})
  
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-1", {"stuffed-2", 2})
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-1", {"mechanical-2", 2})
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-2", {"stuffed-3", 2})
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-2", {"mechanical-3", 2})
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-3", {"stuffed-4", 2})
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-3", {"mechanical-4", 2})
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-4", {"mechanical-5", 1})
  AngelBobExtended.recipe.addtorecipe("bob-area-mining-drill-4", {"stuffed-5", 1})
  
  AngelBobExtended.recipe.addtorecipe("pumpjack", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("pumpjack", {"plumbing-1", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-1", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-1", {"plumbing-2", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-2", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-2", {"plumbing-3", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-3", {"stuffed-4", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-3", {"plumbing-4", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-4", {"stuffed-5", 1})
  AngelBobExtended.recipe.addtorecipe("bob-pumpjack-4", {"plumbing-5", 1})
end
local function replacePower()
  AngelBobExtended.recipe.addtorecipe("boiler", {"heat-resistant-1", 1})
  AngelBobExtended.recipe.addtorecipe("boiler", {"plumbing-1", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-2", {"heat-resistant-2", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-2", {"plumbing-2", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-3", {"heat-resistant-3", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-3", {"plumbing-3", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-4", {"heat-resistant-4", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-4", {"plumbing-4", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-5", {"heat-resistant-5", 1})
  AngelBobExtended.recipe.addtorecipe("boiler-5", {"plumbing-5", 1})
  
  AngelBobExtended.recipe.addtorecipe("oil-boiler", {"heat-resistant-2", 2})
  AngelBobExtended.recipe.addtorecipe("oil-boiler", {"plumbing-2", 2})
  AngelBobExtended.recipe.addtorecipe("oil-boiler-2", {"heat-resistant-3", 2})
  AngelBobExtended.recipe.addtorecipe("oil-boiler-2", {"plumbing-3", 2})
  AngelBobExtended.recipe.addtorecipe("oil-boiler-3", {"heat-resistant-4", 2})
  AngelBobExtended.recipe.addtorecipe("oil-boiler-3", {"plumbing-4", 2})
  AngelBobExtended.recipe.addtorecipe("oil-boiler-4", {"heat-resistant-5", 2})
  AngelBobExtended.recipe.addtorecipe("oil-boiler-4", {"plumbing-5", 2})
  
  data.raw.recipe["nuclear-reactor"].ingredients ={ {"heat-pipe",25},{"advanced-circuit",100},{"refined-concrete",250},{"steel-plate",100}}
  data.raw.recipe["centrifuge"].ingredients ={{"advanced-circuit",20},{"refined-concrete",50},{"steel-plate",20}}
  
  AngelBobExtended.recipe.addtorecipe("nuclear-reactor", {"heat-resistant-3", 20})
  AngelBobExtended.recipe.addtorecipe("nuclear-reactor", {"reinforced-3", 15})
  AngelBobExtended.recipe.addtorecipe("nuclear-reactor", {"plumbing-3", 10})
  AngelBobExtended.recipe.addtorecipe("nuclear-reactor", {"mechanical-3", 5})
  AngelBobExtended.recipe.addtorecipe("nuclear-reactor", {"lead-plate", 150})
  
  AngelBobExtended.recipe.addtorecipe("centrifuge",{"stuffed-3",4})
  AngelBobExtended.recipe.addtorecipe("centrifuge",{"mechanical-3",8})
  AngelBobExtended.recipe.addtorecipe("centrifuge",{"reinforced-3",2})
  AngelBobExtended.recipe.addtorecipe("centrifuge", {"lead-plate", 30})
  
  AngelBobExtended.recipe.addtorecipe("burner-reactor", {"heat-resistant-2", 3})
  AngelBobExtended.recipe.addtorecipe("burner-reactor", {"reinforced-2", 3})
  AngelBobExtended.recipe.addtorecipe("burner-reactor-2", {"heat-resistant-3", 3})
  AngelBobExtended.recipe.addtorecipe("burner-reactor-2", {"reinforced-3", 3})
  AngelBobExtended.recipe.addtorecipe("burner-reactor-3", {"reinforced-4", 3})
  AngelBobExtended.recipe.addtorecipe("burner-reactor-3", {"heat-resistant-4", 3})
  
  AngelBobExtended.recipe.addtorecipe("fluid-reactor", {"heat-resistant-2", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor", {"plumbing-2", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor", {"reinforced-2", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor-2", {"heat-resistant-3", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor-2", {"plumbing-3", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor-2", {"reinforced-3", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor-3", {"heat-resistant-4", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor-3", {"plumbing-4", 4})
  AngelBobExtended.recipe.addtorecipe("fluid-reactor-3", {"reinforced-4", 4})
  
  AngelBobExtended.recipe.addtorecipe("fluid-generator", {"mechanical-2", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator", {"stuffed-2", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator", {"reinforced-2", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator", {"heat-resistant-2", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator", {"plumbing-2", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-2", {"mechanical-3",3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-2", {"stuffed-3",3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-2", {"reinforced-3",3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-2", {"heat-resistant-3",3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-2", {"plumbing-3",3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-3", {"mechanical-4", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-3", {"stuffed-4", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-3", {"reinforced-4", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-3", {"heat-resistant-4", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-3", {"plumbing-4", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-4", {"mechanical-5", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-4", {"stuffed-5", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-4", {"reinforced-5", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-4", {"heat-resistant-5", 3})
  AngelBobExtended.recipe.addtorecipe("fluid-generator-4", {"plumbing-5", 3})
  
  AngelBobExtended.recipe.addtorecipe("steam-engine", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine", {"mechanical-1", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine", {"plumbing-1", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-2", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-2", {"mechanical-2", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-2", {"plumbing-2", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-3", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-3", {"mechanical-3", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-3", {"plumbing-3", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-4", {"stuffed-4", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-4", {"mechanical-4", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-4", {"plumbing-4", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-5", {"stuffed-5", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-5", {"mechanical-5", 1})
  AngelBobExtended.recipe.addtorecipe("steam-engine-5", {"plumbing-5", 1})
  
  AngelBobExtended.recipe.addtorecipe("steam-turbine", {"reinforced-3", 3})
  AngelBobExtended.recipe.addtorecipe("steam-turbine", {"mechanical-3", 4})
  AngelBobExtended.recipe.addtorecipe("steam-turbine", {"stuffed-3", 3})
  AngelBobExtended.recipe.addtorecipe("steam-turbine", {"plumbing-3", 2})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-2", {"reinforced-4", 3})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-2", {"mechanical-4", 4})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-2", {"stuffed-4", 3})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-2", {"plumbing-4", 2})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-3", {"reinforced-5", 3})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-3", {"mechanical-5", 4})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-3", {"stuffed-5", 3})
  AngelBobExtended.recipe.addtorecipe("steam-turbine-3", {"plumbing-5", 2})
  
  if data.raw["item"]["petroleum-generator"] then
    AngelBobExtended.recipe.addtorecipe("petroleum-generator", {"steam-engine-3", 1})
    AngelBobExtended.recipe.addtorecipe("petroleum-generator", {"advanced", 1})
  end
  AngelBobExtended.recipe.addtorecipe("solar-panel-small", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("solar-panel", {"stuffed-2", 3})
  AngelBobExtended.recipe.addtorecipe("solar-panel-large", {"stuffed-2", 5})
  
  AngelBobExtended.recipe.addtorecipe("solar-panel-small-2", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("solar-panel-2", {"stuffed-3", 3})
  AngelBobExtended.recipe.addtorecipe("solar-panel-large-2", {"stuffed-3", 5})
  
  AngelBobExtended.recipe.addtorecipe("solar-panel-small-3", {"stuffed-4", 1})
  AngelBobExtended.recipe.addtorecipe("solar-panel-3", {"stuffed-4", 3})
  AngelBobExtended.recipe.addtorecipe("solar-panel-large-3", {"stuffed-4", 5})
end

local function replaceAngelRefi()

    AngelBobExtended.recipe.addtorecipe("thermal-extractor", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("thermal-extractor", {"plumbing-2", 1})
	AngelBobExtended.recipe.addtorecipe("ore-crusher", {"mechanical-1", 1})
	AngelBobExtended.recipe.addtorecipe("ore-crusher", {"stuffed-1", 1})
    AngelBobExtended.recipe.addtorecipe("ore-crusher-2", {"mechanical-2", 1})
	AngelBobExtended.recipe.addtorecipe("ore-crusher-2", {"stuffed-2", 1})
    AngelBobExtended.recipe.addtorecipe("ore-crusher-3", {"mechanical-3", 1})
	AngelBobExtended.recipe.addtorecipe("ore-crusher-3", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("ore-crusher-4", {"mechanical-4", 1})
	AngelBobExtended.recipe.addtorecipe("ore-crusher-4", {"stuffed-4", 1})
	--AngelBobExtended.recipe.addtorecipe("ore-crusher-5", {"anotherworld", 1})
    
	AngelBobExtended.recipe.addtorecipe("ore-sorting-facility", {"stuffed-1", 2})
	AngelBobExtended.recipe.addtorecipe("ore-sorting-facility", {"mechanical-1", 3})
    AngelBobExtended.recipe.addtorecipe("ore-sorting-facility-2", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("ore-sorting-facility-2", {"mechanical-2", 3})
    AngelBobExtended.recipe.addtorecipe("ore-sorting-facility-3", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("ore-sorting-facility-3", {"mechanical-3", 3})
    AngelBobExtended.recipe.addtorecipe("ore-sorting-facility-4", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("ore-sorting-facility-4", {"mechanical-4", 3})
    
    AngelBobExtended.recipe.addtorecipe("ore-floatation-cell", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("ore-floatation-cell", {"mechanical-2", 1})
	AngelBobExtended.recipe.addtorecipe("ore-floatation-cell", {"plumbing-2", 1})
    AngelBobExtended.recipe.addtorecipe("ore-floatation-cell-2", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("ore-floatation-cell-2", {"mechanical-3", 1})
	AngelBobExtended.recipe.addtorecipe("ore-floatation-cell-2", {"plumbing-3", 1})
    AngelBobExtended.recipe.addtorecipe("ore-floatation-cell-3", {"stuffed-4", 1})
	AngelBobExtended.recipe.addtorecipe("ore-floatation-cell-3", {"mechanical-4", 1})
	AngelBobExtended.recipe.addtorecipe("ore-floatation-cell-3", {"plumbing-4", 1})
	--AngelBobExtended.recipe.addtorecipe("ore-floatation-cell-4", {"anotherworld", 3})
    
    AngelBobExtended.recipe.addtorecipe("ore-leaching-plant", {"reinforced-3", 1})
	AngelBobExtended.recipe.addtorecipe("ore-leaching-plant", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("ore-leaching-plant", {"chemical-3", 3})
    AngelBobExtended.recipe.addtorecipe("ore-leaching-plant-2", {"reinforced-4", 1})
	AngelBobExtended.recipe.addtorecipe("ore-leaching-plant-2", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("ore-leaching-plant-2", {"chemical-4", 3})
    AngelBobExtended.recipe.addtorecipe("ore-leaching-plant-3", {"reinforced-4", 2})
	AngelBobExtended.recipe.addtorecipe("ore-leaching-plant-3", {"stuffed-4", 3})
	AngelBobExtended.recipe.addtorecipe("ore-leaching-plant-3", {"chemical-4", 4})
	--AngelBobExtended.recipe.addtorecipe("ore-leaching-plant-4", {"anotherworld", 4})
    
    AngelBobExtended.recipe.addtorecipe("ore-refinery", {"reinforced-4", 6})
	AngelBobExtended.recipe.addtorecipe("ore-refinery", {"stuffed-4", 4})
	AngelBobExtended.recipe.addtorecipe("ore-refinery", {"chemical-4", 8})
	AngelBobExtended.recipe.addtorecipe("ore-refinery", {"mechanical-4", 4})
	AngelBobExtended.recipe.addtorecipe("ore-refinery", {"heat-resistant-4", 2})
    AngelBobExtended.recipe.addtorecipe("ore-refinery-2", {"reinforced-5", 6})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-2", {"stuffed-5", 4})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-2", {"chemical-5", 8})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-2", {"mechanical-5", 4})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-2", {"heat-resistant-5", 2})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-3", {"reinforced-5", 6})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-3", {"stuffed-5", 4})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-3", {"chemical-5", 8})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-3", {"mechanical-5", 4})
	AngelBobExtended.recipe.addtorecipe("ore-refinery-3", {"heat-resistant-5", 2})
    
    AngelBobExtended.recipe.addtorecipe("filtration-unit", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit", {"mechanical-2", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit", {"plumbing-2", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit", {"chemical-2", 2})
    AngelBobExtended.recipe.addtorecipe("filtration-unit-2", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit-2", {"mechanical-3", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit-2", {"plumbing-3", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit-2", {"chemical-3", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit-3", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit-3", {"mechanical-4", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit-3", {"plumbing-4", 2})
	AngelBobExtended.recipe.addtorecipe("filtration-unit-3", {"chemical-4", 2})
    
    AngelBobExtended.recipe.addtorecipe("crystallizer", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("crystallizer", {"chemical-2", 3})
    AngelBobExtended.recipe.addtorecipe("crystallizer-2", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("crystallizer-2", {"chemical-3", 3})
	AngelBobExtended.recipe.addtorecipe("crystallizer-3", {"stuffed-4", 1})
	AngelBobExtended.recipe.addtorecipe("crystallizer-3", {"chemical-4", 3})
    
    AngelBobExtended.recipe.addtorecipe("hydro-plant", {"stuffed-1", 1})
	AngelBobExtended.recipe.addtorecipe("hydro-plant", {"plumbing-1", 2})
    AngelBobExtended.recipe.addtorecipe("hydro-plant-2", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("hydro-plant-2", {"plumbing-2", 3})
	AngelBobExtended.recipe.addtorecipe("hydro-plant-3", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("hydro-plant-3", {"plumbing-3", 3})
	AngelBobExtended.recipe.addtorecipe("hydro-plant-4", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("hydro-plant-4", {"plumbing-4", 3})
	
	AngelBobExtended.recipe.addtorecipe("washing-plant", {"stuffed-1", 1})
	AngelBobExtended.recipe.addtorecipe("washing-plant", {"plumbing-1", 3})
	AngelBobExtended.recipe.addtorecipe("washing-plant-2", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("washing-plant-2", {"plumbing-2", 3})
	AngelBobExtended.recipe.addtorecipe("washing-plant-3", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("washing-plant-3", {"plumbing-3", 3})
	AngelBobExtended.recipe.addtorecipe("washing-plant-4", {"stuffed-4", 1})
	AngelBobExtended.recipe.addtorecipe("washing-plant-4", {"plumbing-4", 3})
	
	AngelBobExtended.recipe.addtorecipe("clarifier", {"plumbing-1", 1})
	AngelBobExtended.recipe.addtorecipe("clarifier", {"mechanical-1", 1})
	
	AngelBobExtended.recipe.addtorecipe("seafloor-pump", {"stuffed-1", 1})
	AngelBobExtended.recipe.addtorecipe("seafloor-pump", {"plumbing-1", 1})
	AngelBobExtended.recipe.addtorecipe("seafloor-pump", {"mechanical-1", 1})
	
	AngelBobExtended.recipe.addtorecipe("salination-plant", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("salination-plant", {"chemical-2", 1})
	AngelBobExtended.recipe.addtorecipe("salination-plant", {"plumbing-2", 1})
	AngelBobExtended.recipe.addtorecipe("salination-plant-2", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("salination-plant-2", {"chemical-3", 1})
	AngelBobExtended.recipe.addtorecipe("salination-plant-2", {"plumbing-3", 1})
	AngelBobExtended.recipe.addtorecipe("salination-plant-3", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("salination-plant-3", {"chemical-4", 1})
	AngelBobExtended.recipe.addtorecipe("salination-plant-3", {"plumbing-4", 1})
	
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell", {"chemical-3", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell", {"plumbing-3", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell-2", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell-2", {"chemical-4", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell-2", {"plumbing-4", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell-3", {"stuffed-5", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell-3", {"chemical-5", 2})
	AngelBobExtended.recipe.addtorecipe("electro-whinning-cell-3", {"plumbing-5", 2})
	
	AngelBobExtended.recipe.addtorecipe("ore-powderizer", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("ore-powderizer", {"mechanical-2", 1})
	AngelBobExtended.recipe.addtorecipe("ore-powderizer-2", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("ore-powderizer-2", {"mechanical-3", 1})
	AngelBobExtended.recipe.addtorecipe("ore-powderizer-3", {"stuffed-4", 1})
	AngelBobExtended.recipe.addtorecipe("ore-powderizer-3", {"mechanical-4", 1})
	
	AngelBobExtended.recipe.addtorecipe("thermal-bore", {"stuffed-2", 1})
end

local function replaceAngelPetro()

    AngelBobExtended.recipe.addtorecipe("angels-electrolyser", {"chemical-1", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser", {"stuffed-1", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser", {"plumbing-1", 2})
    AngelBobExtended.recipe.addtorecipe("angels-electrolyser-2", {"chemical-2", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser-2", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser-2", {"plumbing-2", 2})
    AngelBobExtended.recipe.addtorecipe("angels-electrolyser-3", {"chemical-3", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser-3", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser-3", {"plumbing-3", 2})
    AngelBobExtended.recipe.addtorecipe("angels-electrolyser-4", {"chemical-4", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser-4", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("angels-electrolyser-4", {"plumbing-4", 2})
	
    AngelBobExtended.recipe.addtorecipe("chemical-plant", {{"stuffed-1", 1},{"chemical-1", 1},{"plumbing-1", 1}})
    AngelBobExtended.recipe.addtorecipe("chemical-plant-2", {{"stuffed-2", 1},{"chemical-2", 1},{"plumbing-2", 1}})
    AngelBobExtended.recipe.addtorecipe("chemical-plant-3", {{"stuffed-3", 1},{"chemical-3", 1},{"plumbing-3", 1}})
    AngelBobExtended.recipe.addtorecipe("chemical-plant-4", {{"stuffed-4", 1},{"chemical-4", 1},{"plumbing-4", 1}})
	
    AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant", {"stuffed-2", 3})
	AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant", {"chemical-2", 3})
	AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant", {"plumbing-2", 2})
    AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant-2", {"stuffed-3", 3})
	AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant-2", {"chemical-3", 3})
	AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant-2", {"plumbing-3", 2})
	AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant-3", {"stuffed-4", 3})
	AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant-3", {"chemical-4", 3})
	AngelBobExtended.recipe.addtorecipe("advanced-chemical-plant-3", {"plumbing-4", 2})
	
    AngelBobExtended.recipe.addtorecipe("gas-refinery", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery", {"chemical-2", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery", {"plumbing-2", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery", {"reinforced-2", 1})
    AngelBobExtended.recipe.addtorecipe("gas-refinery-2", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-2", {"chemical-3", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-2", {"plumbing-3", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-2", {"reinforced-3", 1})
    AngelBobExtended.recipe.addtorecipe("gas-refinery-3", {"stuffed-4", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-3", {"chemical-4", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-3", {"plumbing-4", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-3", {"reinforced-4", 1})
    AngelBobExtended.recipe.addtorecipe("gas-refinery-4", {"stuffed-5", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-4", {"chemical-5", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-4", {"plumbing-5", 1})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-4", {"reinforced-5", 1})
	
    AngelBobExtended.recipe.addtorecipe("separator", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("separator", {"chemical-2", 1})
	AngelBobExtended.recipe.addtorecipe("separator", {"plumbing-2", 1})
	AngelBobExtended.recipe.addtorecipe("separator", {"mechanical-2", 1})
    AngelBobExtended.recipe.addtorecipe("separator-2", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("separator-2", {"chemical-3", 1})
	AngelBobExtended.recipe.addtorecipe("separator-2", {"plumbing-3", 1})
	AngelBobExtended.recipe.addtorecipe("separator-2", {"mechanical-3", 1})
    AngelBobExtended.recipe.addtorecipe("separator-3", {"stuffed-4", 1})
	AngelBobExtended.recipe.addtorecipe("separator-3", {"chemical-4", 1})
	AngelBobExtended.recipe.addtorecipe("separator-3", {"plumbing-4", 1})
	AngelBobExtended.recipe.addtorecipe("separator-3", {"mechanical-4", 1})
    AngelBobExtended.recipe.addtorecipe("separator-4", {"stuffed-5", 1})
	AngelBobExtended.recipe.addtorecipe("separator-4", {"chemical-5", 1})
	AngelBobExtended.recipe.addtorecipe("separator-4", {"plumbing-5", 1})
	AngelBobExtended.recipe.addtorecipe("separator-4", {"mechanical-5", 1})
	
	
	AngelBobExtended.recipe.addtorecipe("angels-flare-stack", {"chemical-2", 1})
	
    AngelBobExtended.recipe.addtorecipe("gas-refinery-small", {"reinforced-2", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small", {"chemical-2", 2})
    AngelBobExtended.recipe.addtorecipe("gas-refinery-small-2", {"reinforced-3", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small-2", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small-2", {"chemical-3", 2})
    AngelBobExtended.recipe.addtorecipe("gas-refinery-small-3", {"reinforced-4", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small-3", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small-3", {"chemical-4", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small-4", {"reinforced-5", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small-4", {"stuffed-5", 2})
	AngelBobExtended.recipe.addtorecipe("gas-refinery-small-4", {"chemical-5", 2})
	
	AngelBobExtended.recipe.addtorecipe("angels-chemical-plant", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("angels-chemical-plant", {"chemical-2", 1})
    AngelBobExtended.recipe.addtorecipe("angels-chemical-plant-2", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("angels-chemical-plant-2", {"chemical-3", 1})
    AngelBobExtended.recipe.addtorecipe("angels-chemical-plant-3", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("angels-chemical-plant-3", {"chemical-3", 2})
    AngelBobExtended.recipe.addtorecipe("angels-chemical-plant-4", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("angels-chemical-plant-4", {"chemical-4", 2})
	
	AngelBobExtended.recipe.addtorecipe("steam-cracker", {"reinforced-2", 1})
	AngelBobExtended.recipe.addtorecipe("steam-cracker", {"stuffed-2", 1})
	AngelBobExtended.recipe.addtorecipe("steam-cracker", {"chemical-2", 1})
	AngelBobExtended.recipe.addtorecipe("steam-cracker", {"plumbing-2", 1})
    AngelBobExtended.recipe.addtorecipe("steam-cracker-2", {"reinforced-3", 1})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-2", {"stuffed-3", 1})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-2", {"chemical-3", 1})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-2", {"plumbing-3", 1})
    AngelBobExtended.recipe.addtorecipe("steam-cracker-3", {"reinforced-3", 2})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-3", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-3", {"chemical-4", 2})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-3", {"plumbing-4", 2})
    AngelBobExtended.recipe.addtorecipe("steam-cracker-4", {"reinforced-5", 2})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-4", {"stuffed-5", 2})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-4", {"chemical-5", 2})
	AngelBobExtended.recipe.addtorecipe("steam-cracker-4", {"plumbing-5", 2})

end

local function replaceAngelMe()

    AngelBobExtended.recipe.addtorecipe("blast-furnace", {"reinforced-1", 3})
	AngelBobExtended.recipe.addtorecipe("blast-furnace", {"heat-resistant-1", 3})
    AngelBobExtended.recipe.addtorecipe("blast-furnace-2", {"reinforced-2", 5})
	AngelBobExtended.recipe.addtorecipe("blast-furnace-2", {"heat-resistant-2", 5})
    AngelBobExtended.recipe.addtorecipe("blast-furnace-3", {"reinforced-3", 5})
	AngelBobExtended.recipe.addtorecipe("blast-furnace-3", {"heat-resistant-3", 5})
    AngelBobExtended.recipe.addtorecipe("blast-furnace-4", {"reinforced-4", 5})
	AngelBobExtended.recipe.addtorecipe("blast-furnace-4", {"heat-resistant-4", 5})
	
    AngelBobExtended.recipe.addtorecipe("induction-furnace", {"reinforced-1", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace", {"stuffed-1", 2})
	AngelBobExtended.recipe.addtorecipe("induction-furnace", {"mechanical-1", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace", {"plumbing-1", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace", {"heat-resistant-1", 2})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-2", {"reinforced-2", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-2", {"mechanical-2", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-2", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-2", {"plumbing-2", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-2", {"heat-resistant-2", 2})
    AngelBobExtended.recipe.addtorecipe("induction-furnace-3", {"reinforced-3", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-3", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-3", {"mechanical-3", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-3", {"plumbing-3", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-3", {"heat-resistant-3", 2})
    AngelBobExtended.recipe.addtorecipe("induction-furnace-4", {"reinforced-4", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-4", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-4", {"mechanical-4", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-4", {"plumbing-4", 1})
	AngelBobExtended.recipe.addtorecipe("induction-furnace-4", {"heat-resistant-4", 2})
	
    AngelBobExtended.recipe.addtorecipe("casting-machine", {"stuffed-1", 1})
	AngelBobExtended.recipe.addtorecipe("casting-machine", {"mechanical-1", 1})
	AngelBobExtended.recipe.addtorecipe("casting-machine", {"plumbing-1", 1})
	AngelBobExtended.recipe.addtorecipe("casting-machine", {"heat-resistant-1", 1})
    AngelBobExtended.recipe.addtorecipe("casting-machine-2", {"stuffed-2", 2})
	AngelBobExtended.recipe.addtorecipe("casting-machine-2", {"mechanical-2", 2})
	AngelBobExtended.recipe.addtorecipe("casting-machine-2", {"plumbing-2", 1})
	AngelBobExtended.recipe.addtorecipe("casting-machine-2", {"heat-resistant-2", 1})
    AngelBobExtended.recipe.addtorecipe("casting-machine-3", {"stuffed-3", 2})
	AngelBobExtended.recipe.addtorecipe("casting-machine-3", {"mechanical-3", 2})
	AngelBobExtended.recipe.addtorecipe("casting-machine-3", {"plumbing-3", 1})
	AngelBobExtended.recipe.addtorecipe("casting-machine-3", {"heat-resistant-3", 1})
    AngelBobExtended.recipe.addtorecipe("casting-machine-4", {"stuffed-4", 2})
	AngelBobExtended.recipe.addtorecipe("casting-machine-4", {"mechanical-4", 2})
	AngelBobExtended.recipe.addtorecipe("casting-machine-4", {"plumbing-4", 1})
	AngelBobExtended.recipe.addtorecipe("casting-machine-4", {"heat-resistant-4", 1})
	
    AngelBobExtended.recipe.addtorecipe("ore-processing-machine", {"mechanical-2", 1})
	AngelBobExtended.recipe.addtorecipe("ore-processing-machine", {"stuffed-2", 1})
    AngelBobExtended.recipe.addtorecipe("ore-processing-machine-2", {"mechanical-2", 2})
	AngelBobExtended.recipe.addtorecipe("ore-processing-machine-2", {"stuffed-2", 2})
    AngelBobExtended.recipe.addtorecipe("ore-processing-machine-3", {"mechanical-3", 2})
	AngelBobExtended.recipe.addtorecipe("ore-processing-machine-3", {"stuffed-3", 2})
    AngelBobExtended.recipe.addtorecipe("ore-processing-machine-4", {"mechanical-4", 2})
	AngelBobExtended.recipe.addtorecipe("ore-processing-machine-4", {"stuffed-4", 2})
	
    AngelBobExtended.recipe.addtorecipe("pellet-press", {"mechanical-2", 5})
	AngelBobExtended.recipe.addtorecipe("pellet-press", {"stuffed-2", 5})
    AngelBobExtended.recipe.addtorecipe("pellet-press-2", {"mechanical-3", 5})
	AngelBobExtended.recipe.addtorecipe("pellet-press-2", {"stuffed-3", 5})
    AngelBobExtended.recipe.addtorecipe("pellet-press-3", {"mechanical-4", 5})
	AngelBobExtended.recipe.addtorecipe("pellet-press-3", {"stuffed-4", 5})
	AngelBobExtended.recipe.addtorecipe("pellet-press-4", {"mechanical-5", 5})
	AngelBobExtended.recipe.addtorecipe("pellet-press-4", {"stuffed-5", 5})
	

end
local function replaceBio()
  AngelBobExtended.recipe.addtorecipe("algae-farm", {"supple-1", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm", {"plumbing-1", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-2", {"supple-2", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-2", {"plumbing-2", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-2", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-3", {"supple-3", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-3", {"plumbing-3", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-3", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-4", {"supple-4", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-4", {"plumbing-4", 1})
  AngelBobExtended.recipe.addtorecipe("algae-farm-4", {"stuffed-4", 1})
  
  AngelBobExtended.recipe.addtorecipe("crop-farm", {"supple-1", 2})
  AngelBobExtended.recipe.addtorecipe("crop-farm", {"plumbing-1", 2})
  AngelBobExtended.recipe.addtorecipe("crop-farm-2", {"supple-2", 2})
  AngelBobExtended.recipe.addtorecipe("crop-farm-3", {"supple-3", 2})
  
  AngelBobExtended.recipe.addtorecipe("composter", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("composter", {"chemical-1", 1})
  AngelBobExtended.recipe.addtorecipe("composter-2", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("composter-2", {"chemical-2", 2})
  AngelBobExtended.recipe.addtorecipe("ccomposter-3", {"stuffed-3", 2})
  AngelBobExtended.recipe.addtorecipe("ccomposter-3", {"chemical-3", 2})
  
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-1", {"supple-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-1", {"stuffed-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-1", {"plumbing-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-2", {"supple-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-2", {"stuffed-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-2", {"plumbing-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-3", {"supple-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-3", {"stuffed-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-desert-3", {"plumbing-3", 2})
  
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-1", {"supple-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-1", {"stuffed-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-1", {"plumbing-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-2", {"supple-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-2", {"stuffed-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-2", {"plumbing-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-3", {"supple-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-3", {"stuffed-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-swamp-3", {"plumbing-3", 2})
  
  
  AngelBobExtended.recipe.addtorecipe("seed-extractor", {"supple-1", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor", {"stuffed-1", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor", {"mechanical-1", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor", {"chemical-1", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-2", {"supple-2", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-2", {"stuffed-2", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-2", {"mechanical-2", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-2", {"chemical-2", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-3", {"supple-3", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-3", {"stuffed-3", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-3", {"mechanical-3", 2})
  AngelBobExtended.recipe.addtorecipe("seed-extractor-3", {"chemical-3", 2})
  
  AngelBobExtended.recipe.addtorecipe("bio-processor", {"supple-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-processor", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-processor", {"chemical-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-processor-2", {"supple-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-processor-2", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-processor-2", {"chemical-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-processor-3", {"supple-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-processor-3", {"stuffed-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-processor-3", {"chemical-3", 2})
  
  AngelBobExtended.recipe.addtorecipe("bio-press", {"supple-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press", {"mechanical-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press", {"plumbing-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-2", {"supple-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-2", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-2", {"mechanical-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-2", {"plumbing-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-3", {"supple-3", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-3", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-3", {"mechanical-3", 1})
  AngelBobExtended.recipe.addtorecipe("bio-press-3", {"plumbing-3", 1})
  
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-1", {"supple-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-1", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-1", {"plumbing-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-2", {"supple-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-2", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-2", {"plumbing-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-3", {"supple-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-3", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("bio-arboretum-3", {"plumbing-3", 1})
  
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-1", {"supple-1", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-1", {"stuffed-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-1", {"plumbing-1", 1})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-2", {"supple-2", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-2", {"stuffed-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-2", {"plumbing-2", 1})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-3", {"supple-3", 2})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-3", {"stuffed-3", 1})
  AngelBobExtended.recipe.addtorecipe("bio-generator-temperate-3", {"plumbing-3", 1})
  
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor", {"supple-1", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor", {"stuffed-1", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor", {"mechanical-1", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor", {"plumbing-1", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-2", {"supple-2", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-2", {"stuffed-2", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-2", {"mechanical-2", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-2", {"plumbing-2", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-3", {"supple-3", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-3", {"stuffed-3", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-3", {"mechanical-3", 1})
   AngelBobExtended.recipe.addtorecipe("nutrient-extractor-3", {"plumbing-3", 1})
  
   AngelBobExtended.recipe.addtorecipe("bio-butchery", {"supple-1", 1})
   AngelBobExtended.recipe.addtorecipe("bio-butchery", {"stuffed-1", 1})
   AngelBobExtended.recipe.addtorecipe("bio-butchery-2", {"supple-2", 1})
   AngelBobExtended.recipe.addtorecipe("bio-butchery-2", {"stuffed-2", 1})
   AngelBobExtended.recipe.addtorecipe("bio-butchery-3", {"supple-3", 1})
   AngelBobExtended.recipe.addtorecipe("bio-butchery-3", {"stuffed-3", 1})
  
   AngelBobExtended.recipe.addtorecipe("bio-hatchery", {"supple-1", 2})
   AngelBobExtended.recipe.addtorecipe("bio-hatchery-2", {"supple-2", 2})
   AngelBobExtended.recipe.addtorecipe("bio-hatchery-3", {"supple-3", 2})
   
   AngelBobExtended.recipe.addtorecipe("bio-refugium-biter", {"supple-1", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-biter-2", {"supple-2", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-biter-3", {"supple-3", 2})
   
   AngelBobExtended.recipe.addtorecipe("bio-refugium-fish", {"supple-1", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-fish-2", {"supple-2", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-fish-3", {"supple-3", 2})
   
   AngelBobExtended.recipe.addtorecipe("bio-refugium-hogger", {"supple-1", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-hogger-2", {"supple-2", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-hogger-3", {"supple-3", 2})
   
   AngelBobExtended.recipe.addtorecipe("bio-refugium-puffer", {"supple-1", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-puffer-2", {"supple-2", 2})
   AngelBobExtended.recipe.addtorecipe("bio-refugium-puffer-3", {"supple-3", 2})
   
  
  
  
end

local function replaceRobot()
  AngelBobExtended.recipe.addtorecipe("bob-roboport-2", {"stuffed-3", 5})
  AngelBobExtended.recipe.addtorecipe("bob-roboport-3", {"stuffed-4", 5})
  AngelBobExtended.recipe.addtorecipe("bob-roboport-4", {"stuffed-5", 5})
end

replaceMachine()
replaceBio()
replaceMining()
replacePower()
replaceAngelRefi()
replaceAngelPetro()
replaceAngelMe()
replaceRobot()